현재 위치 기준 10m 내에 있는 랜드마크 반환 api
playkuround/playkuround-server pull request #19
Opened 2022-09-13 13:10 UTC by redcarrot1

## 요약
- api 응답을 ApiUtils 사용하도록 수정
- 현재 위치 기준 10m 내에 있는 랜드마크 반환 api 추가
- 테스트 수정 및 추가

<br>

## 작업 내용
1. adventure api 응답 폼을 ApiUtils 사용하는 걸로 수정 -> 테스트도 수정

2. adventure 기록 찾기(Get, /api/adventures) api의 응답 폼 중 localdatatime 타입을 @JsonFormat을 이용해서 yyyy-MM-dd HH:mm:ss 형식으로 반환하도록 설정

3. 현재 위치 기준 10m 내에 있는 랜드마크 반환하는 api 추가 (Get, /api/landmarks)
response body 예시는 아래와 같습니다.
```json
{
  "isSuccess":true,
  "response":
    {
      "id": 19,
      "name": "인문학관(인문대)",
      "distance": 0.13425232662457948,
      "gameType": "QUIZ"
    }
}
```
gameType은 `QUIZ`, `TIMER`, `MOON` 중 1개 입니다.

5. 테스트 데이터인 data-h2.sql 생성 -> profile이 test인 경우 실행됩니다.

<br>

## 기타
- api 주소를 `/api/landmarks/near` 로 할까 고민했지만,  `/api/landmarks` 로 결정한 이유는, 랜드마크 조회 api를 따로 제작하지 않을 것이라고 생각했기 때문입니다.
- 주변 10m 이내에 존재하는 landmark가 없을지라도 status는 200으로 설정했습니다. 그 이유는 api 스팩 상 오류나 에러가 아닌, 정상 호출이기 때문입니다. 이 상황에서는 아래와 같이 반환됩니다.
```json
{
  "isSuccess": true,
  "response": {}
}
```

2022-09-14 10:02 UTC, bong01 requested changes

2022-09-14 10:02 UTC, bong01 commented on src/main/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApi.java
> +    public ApiResponse<FindNearLandmark.Response> LandmarkFindNear(@RequestBody @Valid FindNearLandmark.Request findNearLandmark) {
GET 요청이므로 `@RequestBody` 보단 `@RequestParam` 으로 받도록 해야 될 것 같습니다!

2022-09-14 18:37 UTC, redcarrot1 commented on src/main/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApi.java
> +    public ApiResponse<FindNearLandmark.Response> LandmarkFindNear(@RequestBody @Valid FindNearLandmark.Request findNearLandmark) {
수정했습니다.
개인적으로 궁금한게 있는데,
1. Get api는 json형식으로 전송보다는 url param으로 데이터를 받는게 더 좋은가요? 전송해야할 데이터 양이 많아지더라도 파라미터로 전송하나요?
2. '@ReqeustParam`과 `@PathVariable`의 의미상 차이점은 무엇인가요? 예전에는 RequestParam을 많이 사용했는데, 최근 Pathvariable을 사용하는 경우도 많아지는 것 같기도 하고.. 서로 혼용해서 사용하기도 하고.. 참 애매합니다.

2022-09-15 04:32 UTC, bong01 commented on src/main/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApi.java
> +    public ApiResponse<FindNearLandmark.Response> LandmarkFindNear(@RequestBody @Valid FindNearLandmark.Request findNearLandmark) {
1. GET 메서드 사용 시 Body를 지원하지 않는 클라이언트도 있기 때문에 쿼리 파라미터로 받는 것이 더 좋다고 생각했습니다. 전달받을 데이터 양이 많을 시 따로 클래스를 생성하여 객체로 받도록 관리하거나, 특수한 경우엔 Body로 받는 것도 고려해보면 될 것 같습니다.
2. 리소스를 식별할 때는 `@PathVariable`, 리소스들을 정렬이나 필터링 혹은 페이징할 때는 `@RequestParam`을 사용하는게 좋은 것 같습니다.

2022-09-15 04:33 UTC, bong01 approved these changes

2022-09-16 14:15 UTC, KTineil approved these changes

2022-09-19 12:44 UTC, merged